### ISSUE TITLE
Cannot get any output from authenticate.go

### ISSUE THREAD

**Issue by krdchang** [salesforce/pam_oidc#11]
I'm trying to use pam_oidc for ssh but I'm getting no response after a call to discoverAuthenticate. I'm trying to troubleshoot it but I don't know Go all that well. How can I get println statements in the functions in authenticate.go so that I can find the problem?

Thanks,
Dennis

**Comment by krdchang** [comment]
By the way I have placed println and fmt.println statements inside discoverAuthenticate but I'm not seeing any output in /var/log/auth.log.

**Comment by karlhungus** [comment]
Appolgoies for getting to this so much later, probably not all that helpful to you now. You might try calling https://github.com/salesforce/pam_oidc/blob/main/pam_oidc.go#L64.
