### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by hgadatia** [salesforce/pam_oidc#17]
Getting the following error when compiling locally. 

```
go: finding golang.org/x/crypto v0.14.0
# git.dev.pardot.com/pardot/pam_oidc
./pam_oidc.go:13:10: fatal error: security/pam_appl.h: No such file or directory
   13 | #include <security/pam_appl.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:6: pam_oidc.so] Error 2
```

**Comment by hgadatia** [comment]
All set, figured out the issue.

**Comment by tomdev** [comment]
@hgadatia care to share your solution? That sounds useful for other running into the same issue.

**Comment by hgadatia** [comment]
@tomdev  was missing some required dependencies in my build environment.  Just followed this for Ubuntu build environment:

https://stackoverflow.com/questions/15614823/pam-appl-h-and-pam-misc-h-missing-in-rshd-c-source-code
